# Generated by Django 2.1.3 on 2018-11-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181117_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playstation',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
