# Generated by Django 2.1.3 on 2018-11-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181117_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('controllers', models.IntegerField()),
                ('media_type', models.CharField(max_length=60)),
                ('memory_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Playstation',
            new_name='Games',
        ),
    ]
