# Generated by Django 2.1.3 on 2018-11-18 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181117_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('beat', models.BooleanField()),
                ('complete', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.RenameModel(
            old_name='Consoles',
            new_name='Console',
        ),
        migrations.AddField(
            model_name='game',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Console'),
        ),
    ]
